# Generated by Django 2.2 on 2019-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('sub_title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=1)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('video', models.FileField(null=True, upload_to='media')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
