# Generated by Django 2.2 on 2019-07-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
