# Generated by Django 2.2 on 2019-07-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='icon',
            field=models.CharField(max_length=64),
        ),
    ]
