# Generated by Django 2.2 on 2019-07-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_award'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('year',)},
        ),
    ]
